repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        types: [python]
        additional_dependencies:
          - click==8.1.7

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        types: [python]
        additional_dependencies:
          - flake8-bugbear==23.12.2

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: mypy (backend)
        files: ^backend/
        additional_dependencies:
          - pydantic>=2.5
          - sqlalchemy>=2.0
          - types-requests
          - types-python-dateutil
