"""increase account fields length to 50

Revision ID: c10198cd2bcb
Revises: ae3a6d0c14ea
Create Date: 2025-11-16 15:18:52.843112+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10198cd2bcb'
down_revision: Union[str, None] = 'ae3a6d0c14ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase account fields length from 20 to 50 characters
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(20),
               type_=sa.String(50),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(20),
               type_=sa.String(50),
               existing_nullable=True)

    op.alter_column('bank_transactions', 'region',
               existing_type=postgresql.ENUM('MOSCOW', 'SPB', 'REGIONS', 'FOREIGN', name='regionenum'),
               comment=None,
               existing_comment='Регион операции',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'exhibition',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Выставка/мероприятие',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'document_type',
               existing_type=postgresql.ENUM('PAYMENT_ORDER', 'CASH_ORDER', 'INVOICE', 'ACT', 'CONTRACT', 'OTHER', name='documenttypeenum'),
               comment=None,
               existing_comment='Тип документа',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_rub_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Приход в рублях',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_eur_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Приход в евро',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_rub_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Расход в рублях',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_eur_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Расход в евро',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'transaction_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Месяц операции (1-12)',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'transaction_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Год операции',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'expense_acceptance_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Месяц принятия к расходу (1-12)',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'expense_acceptance_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Год принятия к расходу',
               existing_nullable=True)
    op.drop_index('idx_bank_transactions_region', table_name='bank_transactions')
    op.drop_index('idx_bank_transactions_transaction_month', table_name='bank_transactions')
    op.drop_index('idx_bank_transactions_transaction_year', table_name='bank_transactions')
    op.create_index(op.f('ix_bank_transactions_region'), 'bank_transactions', ['region'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_month'), 'bank_transactions', ['transaction_month'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_year'), 'bank_transactions', ['transaction_year'], unique=False)
    op.drop_constraint('fk_fin_contracts_organization_id_fin_organizations', 'fin_contracts', type_='foreignkey')
    op.create_foreign_key(None, 'fin_contracts', 'fin_organizations', ['organization_id'], ['id'])
    op.drop_index('ix_fin_expense_details_unique_detail', table_name='fin_expense_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert account fields length back to 20 characters
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(50),
               type_=sa.String(20),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(50),
               type_=sa.String(20),
               existing_nullable=True)

    op.create_index('ix_fin_expense_details_unique_detail', 'fin_expense_details', ['expense_operation_id', 'payment_type', 'payment_amount', 'department_id'], unique=False)
    op.drop_constraint(None, 'fin_contracts', type_='foreignkey')
    op.create_foreign_key('fk_fin_contracts_organization_id_fin_organizations', 'fin_contracts', 'fin_organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_bank_transactions_transaction_year'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_month'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_region'), table_name='bank_transactions')
    op.create_index('idx_bank_transactions_transaction_year', 'bank_transactions', ['transaction_year'], unique=False)
    op.create_index('idx_bank_transactions_transaction_month', 'bank_transactions', ['transaction_month'], unique=False)
    op.create_index('idx_bank_transactions_region', 'bank_transactions', ['region'], unique=False)
    op.alter_column('bank_transactions', 'expense_acceptance_year',
               existing_type=sa.INTEGER(),
               comment='Год принятия к расходу',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'expense_acceptance_month',
               existing_type=sa.INTEGER(),
               comment='Месяц принятия к расходу (1-12)',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'transaction_year',
               existing_type=sa.INTEGER(),
               comment='Год операции',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'transaction_month',
               existing_type=sa.INTEGER(),
               comment='Месяц операции (1-12)',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_eur_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Расход в евро',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_rub_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Расход в рублях',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_eur_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Приход в евро',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount_rub_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Приход в рублях',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'document_type',
               existing_type=postgresql.ENUM('PAYMENT_ORDER', 'CASH_ORDER', 'INVOICE', 'ACT', 'CONTRACT', 'OTHER', name='documenttypeenum'),
               comment='Тип документа',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'exhibition',
               existing_type=sa.VARCHAR(length=255),
               comment='Выставка/мероприятие',
               existing_nullable=True)
    op.alter_column('bank_transactions', 'region',
               existing_type=postgresql.ENUM('MOSCOW', 'SPB', 'REGIONS', 'FOREIGN', name='regionenum'),
               comment='Регион операции',
               existing_nullable=True)
    # ### end Alembic commands ###
