"""add kpi goal templates for reusable goal sets

Revision ID: 54c62e6d65b3
Revises: 7a3e45e487e0
Create Date: 2025-11-20 07:34:57.990675+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c62e6d65b3'
down_revision: Union[str, None] = '7a3e45e487e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_goal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_template_dept_active', 'kpi_goal_templates', ['department_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_kpi_goal_templates_department_id'), 'kpi_goal_templates', ['department_id'], unique=False)
    op.create_index(op.f('ix_kpi_goal_templates_id'), 'kpi_goal_templates', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_goal_templates_is_active'), 'kpi_goal_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_kpi_goal_templates_name'), 'kpi_goal_templates', ['name'], unique=False)
    op.create_table('kpi_goal_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['kpi_goals.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['kpi_goal_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_item_goal', 'kpi_goal_template_items', ['goal_id'], unique=False)
    op.create_index('idx_template_item_template', 'kpi_goal_template_items', ['template_id'], unique=False)
    op.create_index(op.f('ix_kpi_goal_template_items_goal_id'), 'kpi_goal_template_items', ['goal_id'], unique=False)
    op.create_index(op.f('ix_kpi_goal_template_items_id'), 'kpi_goal_template_items', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_goal_template_items_template_id'), 'kpi_goal_template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_goal_template_items_template_id'), table_name='kpi_goal_template_items')
    op.drop_index(op.f('ix_kpi_goal_template_items_id'), table_name='kpi_goal_template_items')
    op.drop_index(op.f('ix_kpi_goal_template_items_goal_id'), table_name='kpi_goal_template_items')
    op.drop_index('idx_template_item_template', table_name='kpi_goal_template_items')
    op.drop_index('idx_template_item_goal', table_name='kpi_goal_template_items')
    op.drop_table('kpi_goal_template_items')
    op.drop_index(op.f('ix_kpi_goal_templates_name'), table_name='kpi_goal_templates')
    op.drop_index(op.f('ix_kpi_goal_templates_is_active'), table_name='kpi_goal_templates')
    op.drop_index(op.f('ix_kpi_goal_templates_id'), table_name='kpi_goal_templates')
    op.drop_index(op.f('ix_kpi_goal_templates_department_id'), table_name='kpi_goal_templates')
    op.drop_index('idx_kpi_template_dept_active', table_name='kpi_goal_templates')
    op.drop_table('kpi_goal_templates')
    # ### end Alembic commands ###
