"""add admin_settings table

Revision ID: d3f25188bf40
Revises: 4bc720b19d82
Create Date: 2025-11-20 05:10:39.561988+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f25188bf40'
down_revision: Union[str, None] = '4bc720b19d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('odata_url', sa.String(length=500), nullable=True),
    sa.Column('odata_username', sa.String(length=255), nullable=True),
    sa.Column('odata_password', sa.String(length=255), nullable=True),
    sa.Column('odata_custom_auth_token', sa.Text(), nullable=True),
    sa.Column('vsegpt_api_key', sa.String(length=500), nullable=True),
    sa.Column('vsegpt_base_url', sa.String(length=500), nullable=True),
    sa.Column('vsegpt_model', sa.String(length=255), nullable=True),
    sa.Column('credit_portfolio_ftp_host', sa.String(length=255), nullable=True),
    sa.Column('credit_portfolio_ftp_user', sa.String(length=255), nullable=True),
    sa.Column('credit_portfolio_ftp_password', sa.String(length=255), nullable=True),
    sa.Column('credit_portfolio_ftp_remote_dir', sa.String(length=500), nullable=True),
    sa.Column('credit_portfolio_ftp_local_dir', sa.String(length=500), nullable=True),
    sa.Column('scheduler_enabled', sa.Boolean(), nullable=False),
    sa.Column('credit_portfolio_import_enabled', sa.Boolean(), nullable=False),
    sa.Column('credit_portfolio_import_hour', sa.Integer(), nullable=False),
    sa.Column('credit_portfolio_import_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
