"""add bitrix24 integration fields to expenses and contractors

Revision ID: 22fbd61c50d0
Revises: 49720a832653
Create Date: 2025-11-14 11:45:59.234508+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fbd61c50d0'
down_revision: Union[str, None] = '49720a832653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('bitrix_company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contractors_bitrix_company_id'), 'contractors', ['bitrix_company_id'], unique=False)
    op.add_column('expenses', sa.Column('bitrix_task_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('bitrix_task_url', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('bitrix_sync_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_expenses_bitrix_task_id'), 'expenses', ['bitrix_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_bitrix_task_id'), table_name='expenses')
    op.drop_column('expenses', 'bitrix_sync_at')
    op.drop_column('expenses', 'bitrix_task_url')
    op.drop_column('expenses', 'bitrix_task_id')
    op.drop_index(op.f('ix_contractors_bitrix_company_id'), table_name='contractors')
    op.drop_column('contractors', 'bitrix_company_id')
    # ### end Alembic commands ###
