"""add task complexity bonus fields to employee_kpis

Revision ID: 7265be4a81c3
Revises: ec829dfc2a97
Create Date: 2025-11-19 20:26:59.851507+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7265be4a81c3'
down_revision: Union[str, None] = 'ec829dfc2a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_kpi_goal_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='kpitaskstatusenum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='kpitaskpriorityenum'), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_kpi_goal_id'], ['employee_kpi_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_task_due_date', 'kpi_tasks', ['due_date'], unique=False)
    op.create_index('idx_kpi_task_employee', 'kpi_tasks', ['employee_id'], unique=False)
    op.create_index('idx_kpi_task_goal', 'kpi_tasks', ['employee_kpi_goal_id'], unique=False)
    op.create_index('idx_kpi_task_priority', 'kpi_tasks', ['priority'], unique=False)
    op.create_index('idx_kpi_task_status', 'kpi_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_assigned_by_id'), 'kpi_tasks', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_department_id'), 'kpi_tasks', ['department_id'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_due_date'), 'kpi_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_employee_id'), 'kpi_tasks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_employee_kpi_goal_id'), 'kpi_tasks', ['employee_kpi_goal_id'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_id'), 'kpi_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_priority'), 'kpi_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_kpi_tasks_status'), 'kpi_tasks', ['status'], unique=False)
    op.alter_column('budget_categories', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Create enum type for employee KPI status (needed for add_column)
    employee_kpi_status_enum = sa.Enum('DRAFT', 'IN_PROGRESS', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='employeekpistatusenum')
    employee_kpi_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('employee_kpis', sa.Column('depremium_threshold', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('depremium_applied', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('employee_kpis', sa.Column('task_complexity_avg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('task_complexity_multiplier', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('employee_kpis', sa.Column('task_complexity_weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('monthly_bonus_complexity', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('quarterly_bonus_complexity', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('annual_bonus_complexity', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employee_kpis', sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='employeekpistatusenum'), nullable=False, server_default='DRAFT'))
    op.add_column('employee_kpis', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('employee_kpis', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('employee_kpis', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('employee_kpis', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_employee_kpis_status'), 'employee_kpis', ['status'], unique=False)
    op.create_foreign_key(None, 'employee_kpis', 'users', ['reviewed_by_id'], ['id'])
    op.create_index(op.f('ix_payroll_scenario_details_employee_id'), 'payroll_scenario_details', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_scenario_details_scenario_id'), 'payroll_scenario_details', ['scenario_id'], unique=False)
    # Skipping tax_rates.department_id NOT NULL change (data integrity issue)
    # op.alter_column('tax_rates', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping tax_rates.department_id nullable revert (data integrity issue)
    # op.alter_column('tax_rates', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_index(op.f('ix_payroll_scenario_details_scenario_id'), table_name='payroll_scenario_details')
    op.drop_index(op.f('ix_payroll_scenario_details_employee_id'), table_name='payroll_scenario_details')
    op.drop_constraint(None, 'employee_kpis', type_='foreignkey')
    op.drop_index(op.f('ix_employee_kpis_status'), table_name='employee_kpis')
    op.drop_column('employee_kpis', 'rejection_reason')
    op.drop_column('employee_kpis', 'reviewed_at')
    op.drop_column('employee_kpis', 'reviewed_by_id')
    op.drop_column('employee_kpis', 'submitted_at')
    op.drop_column('employee_kpis', 'status')
    op.drop_column('employee_kpis', 'annual_bonus_complexity')
    op.drop_column('employee_kpis', 'quarterly_bonus_complexity')
    op.drop_column('employee_kpis', 'monthly_bonus_complexity')
    op.drop_column('employee_kpis', 'task_complexity_weight')
    op.drop_column('employee_kpis', 'task_complexity_multiplier')
    op.drop_column('employee_kpis', 'task_complexity_avg')
    op.drop_column('employee_kpis', 'depremium_applied')
    op.drop_column('employee_kpis', 'depremium_threshold')
    # Drop employee KPI status enum
    sa.Enum(name='employeekpistatusenum').drop(op.get_bind(), checkfirst=True)
    op.alter_column('budget_categories', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_kpi_tasks_status'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_priority'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_id'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_employee_kpi_goal_id'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_employee_id'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_due_date'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_department_id'), table_name='kpi_tasks')
    op.drop_index(op.f('ix_kpi_tasks_assigned_by_id'), table_name='kpi_tasks')
    op.drop_index('idx_kpi_task_status', table_name='kpi_tasks')
    op.drop_index('idx_kpi_task_priority', table_name='kpi_tasks')
    op.drop_index('idx_kpi_task_goal', table_name='kpi_tasks')
    op.drop_index('idx_kpi_task_employee', table_name='kpi_tasks')
    op.drop_index('idx_kpi_task_due_date', table_name='kpi_tasks')
    op.drop_table('kpi_tasks')
    # ### end Alembic commands ###
