"""add is_baseline field to budget_versions

Revision ID: 93e38b6e59d4
Revises: ac976a594e2f
Create Date: 2025-10-29 11:19:06.015291+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e38b6e59d4'
down_revision: Union[str, None] = 'ac976a594e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('budget_versions', sa.Column('is_baseline', sa.Boolean(), nullable=True))
    # Set default value False for existing rows
    op.execute("UPDATE budget_versions SET is_baseline = FALSE WHERE is_baseline IS NULL")
    # Now make it NOT NULL
    op.alter_column('budget_versions', 'is_baseline', nullable=False)
    # Create index
    op.create_index(op.f('ix_budget_versions_is_baseline'), 'budget_versions', ['is_baseline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_versions_is_baseline'), table_name='budget_versions')
    op.drop_column('budget_versions', 'is_baseline')
    # ### end Alembic commands ###
