"""add module system tables for feature enablement

Revision ID: c236b2acea09
Revises: 2025_11_19_2124
Create Date: 2025-11-19 21:47:04.049686+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c236b2acea09'
down_revision: Union[str, None] = '2025_11_19_2124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_is_active'), 'modules', ['is_active'], unique=False)
    op.create_table('module_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MODULE_ENABLED', 'MODULE_DISABLED', 'MODULE_EXPIRED', 'LIMIT_EXCEEDED', 'LIMIT_WARNING', 'ACCESS_DENIED', 'MODULE_UPDATED', name='moduleeventtypeenum'), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_module_event_created', 'module_events', ['created_at'], unique=False)
    op.create_index('idx_module_event_org_module', 'module_events', ['organization_id', 'module_id'], unique=False)
    op.create_index('idx_module_event_type', 'module_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_module_events_created_at'), 'module_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_module_events_event_type'), 'module_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_module_events_id'), 'module_events', ['id'], unique=False)
    op.create_index(op.f('ix_module_events_module_id'), 'module_events', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_events_organization_id'), 'module_events', ['organization_id'], unique=False)
    op.create_table('organization_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enabled_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enabled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_module_active', 'organization_modules', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_org_module_expires', 'organization_modules', ['expires_at'], unique=False)
    op.create_index('idx_org_module_org_module', 'organization_modules', ['organization_id', 'module_id'], unique=True)
    op.create_index(op.f('ix_organization_modules_id'), 'organization_modules', ['id'], unique=False)
    op.create_index(op.f('ix_organization_modules_is_active'), 'organization_modules', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_modules_module_id'), 'organization_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_organization_modules_organization_id'), 'organization_modules', ['organization_id'], unique=False)
    op.create_table('feature_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_module_id', sa.Integer(), nullable=False),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('current_usage', sa.Integer(), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=True),
    sa.Column('warning_sent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_module_id'], ['organization_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_limit_org_module', 'feature_limits', ['organization_module_id', 'limit_type'], unique=False)
    op.create_index(op.f('ix_feature_limits_id'), 'feature_limits', ['id'], unique=False)
    op.create_index(op.f('ix_feature_limits_limit_type'), 'feature_limits', ['limit_type'], unique=False)
    op.create_index(op.f('ix_feature_limits_organization_module_id'), 'feature_limits', ['organization_module_id'], unique=False)
    # Commented out tax_rates changes - not related to module system
    # op.alter_column('tax_rates', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out tax_rates changes - not related to module system
    # op.alter_column('tax_rates', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_index(op.f('ix_feature_limits_organization_module_id'), table_name='feature_limits')
    op.drop_index(op.f('ix_feature_limits_limit_type'), table_name='feature_limits')
    op.drop_index(op.f('ix_feature_limits_id'), table_name='feature_limits')
    op.drop_index('idx_feature_limit_org_module', table_name='feature_limits')
    op.drop_table('feature_limits')
    op.drop_index(op.f('ix_organization_modules_organization_id'), table_name='organization_modules')
    op.drop_index(op.f('ix_organization_modules_module_id'), table_name='organization_modules')
    op.drop_index(op.f('ix_organization_modules_is_active'), table_name='organization_modules')
    op.drop_index(op.f('ix_organization_modules_id'), table_name='organization_modules')
    op.drop_index('idx_org_module_org_module', table_name='organization_modules')
    op.drop_index('idx_org_module_expires', table_name='organization_modules')
    op.drop_index('idx_org_module_active', table_name='organization_modules')
    op.drop_table('organization_modules')
    op.drop_index(op.f('ix_module_events_organization_id'), table_name='module_events')
    op.drop_index(op.f('ix_module_events_module_id'), table_name='module_events')
    op.drop_index(op.f('ix_module_events_id'), table_name='module_events')
    op.drop_index(op.f('ix_module_events_event_type'), table_name='module_events')
    op.drop_index(op.f('ix_module_events_created_at'), table_name='module_events')
    op.drop_index('idx_module_event_type', table_name='module_events')
    op.drop_index('idx_module_event_org_module', table_name='module_events')
    op.drop_index('idx_module_event_created', table_name='module_events')
    op.drop_table('module_events')
    op.drop_index(op.f('ix_modules_is_active'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
