"""increase account fields length to 50

Revision ID: c10198cd2bcb
Revises: ae3a6d0c14ea
Create Date: 2025-11-16 15:18:52.843112+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10198cd2bcb'
down_revision: Union[str, None] = 'ae3a6d0c14ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase account fields length from 20 to 50 characters
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(20),
               type_=sa.String(50),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(20),
               type_=sa.String(50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert account fields length back to 20 characters
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(50),
               type_=sa.String(20),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(50),
               type_=sa.String(20),
               existing_nullable=True)
    # ### end Alembic commands ###
