"""add income tax fields to payroll_actuals

Revision ID: ac976a594e2f
Revises: 5c5af3ac5381
Create Date: 2025-10-28 21:07:27.116046+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac976a594e2f'
down_revision: Union[str, None] = '5c5af3ac5381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_budget_version_baseline', table_name='budget_versions')
    op.drop_column('budget_versions', 'is_baseline')
    op.execute("ALTER TABLE employee_kpi_goals ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE employee_kpi_goals ALTER COLUMN status TYPE kpigoalstatusenum USING status::text::kpigoalstatusenum")
    op.execute("ALTER TABLE employee_kpi_goals ALTER COLUMN status SET DEFAULT 'ACTIVE'::kpigoalstatusenum")
    op.drop_index('idx_employee_kpi_goals_employee_id', table_name='employee_kpi_goals')
    op.drop_index('idx_employee_kpi_goals_employee_kpi_id', table_name='employee_kpi_goals')
    op.drop_index('idx_employee_kpi_goals_goal_id', table_name='employee_kpi_goals')
    op.drop_index('idx_employee_kpi_goals_month', table_name='employee_kpi_goals')
    op.drop_index('idx_employee_kpi_goals_year', table_name='employee_kpi_goals')
    op.create_index(op.f('ix_employee_kpi_goals_employee_id'), 'employee_kpi_goals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_kpi_goals_employee_kpi_id'), 'employee_kpi_goals', ['employee_kpi_id'], unique=False)
    op.create_index(op.f('ix_employee_kpi_goals_goal_id'), 'employee_kpi_goals', ['goal_id'], unique=False)
    op.create_index(op.f('ix_employee_kpi_goals_id'), 'employee_kpi_goals', ['id'], unique=False)
    op.create_index(op.f('ix_employee_kpi_goals_month'), 'employee_kpi_goals', ['month'], unique=False)
    op.create_index(op.f('ix_employee_kpi_goals_year'), 'employee_kpi_goals', ['year'], unique=False)
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN monthly_bonus_type DROP DEFAULT")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN monthly_bonus_type TYPE bonustypeenum USING monthly_bonus_type::text::bonustypeenum")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN monthly_bonus_type SET DEFAULT 'PERFORMANCE_BASED'::bonustypeenum")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN quarterly_bonus_type DROP DEFAULT")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN quarterly_bonus_type TYPE bonustypeenum USING quarterly_bonus_type::text::bonustypeenum")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN quarterly_bonus_type SET DEFAULT 'PERFORMANCE_BASED'::bonustypeenum")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN annual_bonus_type DROP DEFAULT")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN annual_bonus_type TYPE bonustypeenum USING annual_bonus_type::text::bonustypeenum")
    op.execute("ALTER TABLE employee_kpis ALTER COLUMN annual_bonus_type SET DEFAULT 'PERFORMANCE_BASED'::bonustypeenum")
    op.drop_index('idx_employee_kpis_employee_id', table_name='employee_kpis')
    op.create_index(op.f('ix_employee_kpis_department_id'), 'employee_kpis', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_kpis_employee_id'), 'employee_kpis', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_kpis_id'), 'employee_kpis', ['id'], unique=False)
    op.create_index(op.f('ix_employee_kpis_month'), 'employee_kpis', ['month'], unique=False)
    op.create_index(op.f('ix_employee_kpis_year'), 'employee_kpis', ['year'], unique=False)
    op.execute("ALTER TABLE kpi_goals ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE kpi_goals ALTER COLUMN status TYPE kpigoalstatusenum USING status::text::kpigoalstatusenum")
    op.execute("ALTER TABLE kpi_goals ALTER COLUMN status SET DEFAULT 'DRAFT'::kpigoalstatusenum")
    op.drop_index('idx_kpi_goals_category', table_name='kpi_goals')
    op.drop_index('idx_kpi_goals_name', table_name='kpi_goals')
    op.drop_index('idx_kpi_goals_year', table_name='kpi_goals')
    op.create_index(op.f('ix_kpi_goals_category'), 'kpi_goals', ['category'], unique=False)
    op.create_index(op.f('ix_kpi_goals_department_id'), 'kpi_goals', ['department_id'], unique=False)
    op.create_index(op.f('ix_kpi_goals_id'), 'kpi_goals', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_goals_name'), 'kpi_goals', ['name'], unique=False)
    op.create_index(op.f('ix_kpi_goals_status'), 'kpi_goals', ['status'], unique=False)
    op.create_index(op.f('ix_kpi_goals_year'), 'kpi_goals', ['year'], unique=False)
    op.add_column('payroll_actuals', sa.Column('income_tax_rate', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.13'))
    op.add_column('payroll_actuals', sa.Column('income_tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('payroll_actuals', sa.Column('social_tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.drop_column('payroll_actuals', 'bonus_paid')
    op.drop_column('payroll_plans', 'bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_plans', sa.Column('bonus', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('payroll_actuals', sa.Column('bonus_paid', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_column('payroll_actuals', 'social_tax_amount')
    op.drop_column('payroll_actuals', 'income_tax_amount')
    op.drop_column('payroll_actuals', 'income_tax_rate')
    op.drop_index(op.f('ix_kpi_goals_year'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_status'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_name'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_id'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_department_id'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_category'), table_name='kpi_goals')
    op.create_index('idx_kpi_goals_year', 'kpi_goals', ['year'], unique=False)
    op.create_index('idx_kpi_goals_name', 'kpi_goals', ['name'], unique=False)
    op.create_index('idx_kpi_goals_category', 'kpi_goals', ['category'], unique=False)
    op.alter_column('kpi_goals', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ACHIEVED', 'NOT_ACHIEVED', 'CANCELLED', name='kpigoalstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_index(op.f('ix_employee_kpis_year'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_month'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_id'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_employee_id'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_department_id'), table_name='employee_kpis')
    op.create_index('idx_employee_kpis_employee_id', 'employee_kpis', ['employee_id'], unique=False)
    op.alter_column('employee_kpis', 'annual_bonus_type',
               existing_type=sa.Enum('PERFORMANCE_BASED', 'FIXED', 'MIXED', name='bonustypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PERFORMANCE_BASED'::character varying"))
    op.alter_column('employee_kpis', 'quarterly_bonus_type',
               existing_type=sa.Enum('PERFORMANCE_BASED', 'FIXED', 'MIXED', name='bonustypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PERFORMANCE_BASED'::character varying"))
    op.alter_column('employee_kpis', 'monthly_bonus_type',
               existing_type=sa.Enum('PERFORMANCE_BASED', 'FIXED', 'MIXED', name='bonustypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PERFORMANCE_BASED'::character varying"))
    op.drop_index(op.f('ix_employee_kpi_goals_year'), table_name='employee_kpi_goals')
    op.drop_index(op.f('ix_employee_kpi_goals_month'), table_name='employee_kpi_goals')
    op.drop_index(op.f('ix_employee_kpi_goals_id'), table_name='employee_kpi_goals')
    op.drop_index(op.f('ix_employee_kpi_goals_goal_id'), table_name='employee_kpi_goals')
    op.drop_index(op.f('ix_employee_kpi_goals_employee_kpi_id'), table_name='employee_kpi_goals')
    op.drop_index(op.f('ix_employee_kpi_goals_employee_id'), table_name='employee_kpi_goals')
    op.create_index('idx_employee_kpi_goals_year', 'employee_kpi_goals', ['year'], unique=False)
    op.create_index('idx_employee_kpi_goals_month', 'employee_kpi_goals', ['month'], unique=False)
    op.create_index('idx_employee_kpi_goals_goal_id', 'employee_kpi_goals', ['goal_id'], unique=False)
    op.create_index('idx_employee_kpi_goals_employee_kpi_id', 'employee_kpi_goals', ['employee_kpi_id'], unique=False)
    op.create_index('idx_employee_kpi_goals_employee_id', 'employee_kpi_goals', ['employee_id'], unique=False)
    op.alter_column('employee_kpi_goals', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ACHIEVED', 'NOT_ACHIEVED', 'CANCELLED', name='kpigoalstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.add_column('budget_versions', sa.Column('is_baseline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('idx_budget_version_baseline', 'budget_versions', ['department_id', 'year', 'is_baseline'], unique=False)
    # ### end Alembic commands ###
