"""add business_operation to bank_transactions

Revision ID: d6b65a878d77
Revises: increase_bik_20251117
Create Date: 2025-11-17 11:13:21.069338+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b65a878d77'
down_revision: Union[str, None] = 'increase_bik_20251117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('business_operation', sa.String(length=100), nullable=True))
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_bank_transactions_business_operation'), 'bank_transactions', ['business_operation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_business_operation'), table_name='bank_transactions')
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('bank_transactions', 'business_operation')
    # ### end Alembic commands ###
