"""add quarterly and annual bonus to payroll scenario details

Revision ID: 02f520978e61
Revises: 54c62e6d65b3
Create Date: 2025-11-20 08:38:07.228887+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f520978e61'
down_revision: Union[str, None] = '54c62e6d65b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_scenario_details', sa.Column('quarterly_bonus', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('payroll_scenario_details', sa.Column('annual_bonus', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    # Removed tax_rates.department_id change - causes issues with existing NULL values
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_scenario_details', 'annual_bonus')
    op.drop_column('payroll_scenario_details', 'quarterly_bonus')
    # ### end Alembic commands ###
