"""add business_operation_mappings table for flexible mapping

Revision ID: 181275141cb7
Revises: d6b65a878d77
Create Date: 2025-11-17 11:22:30.589412+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181275141cb7'
down_revision: Union[str, None] = 'd6b65a878d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_operation_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_operation', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_operation_mapping_unique', 'business_operation_mappings', ['business_operation', 'department_id', 'category_id'], unique=True)
    op.create_index(op.f('ix_business_operation_mappings_business_operation'), 'business_operation_mappings', ['business_operation'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_category_id'), 'business_operation_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_department_id'), 'business_operation_mappings', ['department_id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_id'), 'business_operation_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_is_active'), 'business_operation_mappings', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_operation_mappings_is_active'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_department_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_category_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_business_operation'), table_name='business_operation_mappings')
    op.drop_index('ix_business_operation_mapping_unique', table_name='business_operation_mappings')
    op.drop_table('business_operation_mappings')
    # ### end Alembic commands ###
