"""add payment_source to bank_transactions

Revision ID: 6bad3b34ad66
Revises: faf79e6ef6e8
Create Date: 2025-11-17 06:12:01.422466+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bad3b34ad66'
down_revision: Union[str, None] = 'faf79e6ef6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    payment_source_enum = sa.Enum('BANK', 'CASH', name='paymentsourceenum')
    payment_source_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('bank_transactions', sa.Column('payment_source', sa.Enum('BANK', 'CASH', name='paymentsourceenum'), nullable=True))
    op.create_index(op.f('ix_bank_transactions_payment_source'), 'bank_transactions', ['payment_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_payment_source'), table_name='bank_transactions')
    op.drop_column('bank_transactions', 'payment_source')

    # Drop enum type
    payment_source_enum = sa.Enum('BANK', 'CASH', name='paymentsourceenum')
    payment_source_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
