"""add_timesheet_tables_hr_department

Revision ID: 509126e8026b
Revises: 9c03a52a443e
Create Date: 2025-11-20 09:39:38.916518+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509126e8026b'
down_revision: Union[str, None] = '9c03a52a443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_timesheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_days_worked', sa.Integer(), nullable=False),
    sa.Column('total_hours_worked', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='timesheetstatusenum'), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('daily_summary', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_timesheet_month'),
    sa.CheckConstraint('total_days_worked >= 0 AND total_days_worked <= 31', name='ck_timesheet_days'),
    sa.CheckConstraint('total_hours_worked >= 0', name='ck_timesheet_hours'),
    sa.CheckConstraint('year >= 2020 AND year <= 2100', name='ck_timesheet_year'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'department_id', 'year', 'month', name='uq_timesheet_employee_period')
    )
    op.create_index('ix_timesheet_department_period', 'work_timesheets', ['department_id', 'year', 'month'], unique=False)
    op.create_index('ix_timesheet_employee_period', 'work_timesheets', ['employee_id', 'year', 'month'], unique=False)
    op.create_index('ix_timesheet_period', 'work_timesheets', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_work_timesheets_department_id'), 'work_timesheets', ['department_id'], unique=False)
    op.create_index(op.f('ix_work_timesheets_employee_id'), 'work_timesheets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_timesheets_month'), 'work_timesheets', ['month'], unique=False)
    op.create_index(op.f('ix_work_timesheets_status'), 'work_timesheets', ['status'], unique=False)
    op.create_index(op.f('ix_work_timesheets_year'), 'work_timesheets', ['year'], unique=False)
    op.create_table('daily_work_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('break_hours', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('break_hours >= 0', name='ck_break_hours'),
    sa.CheckConstraint('hours_worked >= 0 AND hours_worked <= 24', name='ck_daily_hours'),
    sa.CheckConstraint('overtime_hours >= 0', name='ck_overtime_hours'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['work_timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timesheet_id', 'work_date', name='uq_daily_record_timesheet_date')
    )
    op.create_index('ix_daily_record_date', 'daily_work_records', ['work_date'], unique=False)
    op.create_index('ix_daily_record_department', 'daily_work_records', ['department_id'], unique=False)
    op.create_index('ix_daily_record_timesheet_date', 'daily_work_records', ['timesheet_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_daily_work_records_department_id'), 'daily_work_records', ['department_id'], unique=False)
    op.create_index(op.f('ix_daily_work_records_timesheet_id'), 'daily_work_records', ['timesheet_id'], unique=False)
    op.create_index(op.f('ix_daily_work_records_work_date'), 'daily_work_records', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_work_records_work_date'), table_name='daily_work_records')
    op.drop_index(op.f('ix_daily_work_records_timesheet_id'), table_name='daily_work_records')
    op.drop_index(op.f('ix_daily_work_records_department_id'), table_name='daily_work_records')
    op.drop_index('ix_daily_record_timesheet_date', table_name='daily_work_records')
    op.drop_index('ix_daily_record_department', table_name='daily_work_records')
    op.drop_index('ix_daily_record_date', table_name='daily_work_records')
    op.drop_table('daily_work_records')
    op.drop_index(op.f('ix_work_timesheets_year'), table_name='work_timesheets')
    op.drop_index(op.f('ix_work_timesheets_status'), table_name='work_timesheets')
    op.drop_index(op.f('ix_work_timesheets_month'), table_name='work_timesheets')
    op.drop_index(op.f('ix_work_timesheets_employee_id'), table_name='work_timesheets')
    op.drop_index(op.f('ix_work_timesheets_department_id'), table_name='work_timesheets')
    op.drop_index('ix_timesheet_period', table_name='work_timesheets')
    op.drop_index('ix_timesheet_employee_period', table_name='work_timesheets')
    op.drop_index('ix_timesheet_department_period', table_name='work_timesheets')
    op.drop_table('work_timesheets')
    # ### end Alembic commands ###
