"""add salary_type and gross_net fields to employees

Revision ID: 4bc720b19d82
Revises: c236b2acea09
Create Date: 2025-11-19 22:17:49.303429+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc720b19d82'
down_revision: Union[str, None] = 'c236b2acea09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE salarytypeenum AS ENUM ('GROSS', 'NET')")

    # Now add the columns
    op.add_column('employees', sa.Column('salary_type', sa.Enum('GROSS', 'NET', name='salarytypeenum'), nullable=False, server_default='GROSS'))
    op.add_column('employees', sa.Column('base_salary_gross', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employees', sa.Column('base_salary_net', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employees', sa.Column('ndfl_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('employees', sa.Column('ndfl_rate', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.13'))
    op.create_index(op.f('ix_employees_salary_type'), 'employees', ['salary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_salary_type'), table_name='employees')
    op.drop_column('employees', 'ndfl_rate')
    op.drop_column('employees', 'ndfl_amount')
    op.drop_column('employees', 'base_salary_net')
    op.drop_column('employees', 'base_salary_gross')
    op.drop_column('employees', 'salary_type')

    # Drop the enum type after dropping the column
    op.execute("DROP TYPE salarytypeenum")
    # ### end Alembic commands ###
