"""add_users_table

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2025-10-25 00:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create UserRoleEnum
    op.execute("CREATE TYPE userroleenum AS ENUM ('ADMIN', 'ACCOUNTANT', 'REQUESTER')")

    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'REQUESTER', name='userroleenum'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('department', sa.String(length=255), nullable=True),
        sa.Column('position', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Update dashboard_configs table to use Integer foreign key for user_id
    # First, drop the old user_id column
    op.drop_index('ix_dashboard_configs_user_id', table_name='dashboard_configs')
    op.drop_column('dashboard_configs', 'user_id')

    # Add new user_id column as Integer with foreign key
    op.add_column('dashboard_configs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dashboard_configs_user_id'), 'dashboard_configs', ['user_id'], unique=False)
    op.create_foreign_key('fk_dashboard_configs_user_id', 'dashboard_configs', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert dashboard_configs changes
    op.drop_constraint('fk_dashboard_configs_user_id', 'dashboard_configs', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_configs_user_id'), table_name='dashboard_configs')
    op.drop_column('dashboard_configs', 'user_id')

    # Add back old user_id column as String
    op.add_column('dashboard_configs', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index('ix_dashboard_configs_user_id', 'dashboard_configs', ['user_id'], unique=False)

    # Drop users table
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')

    # Drop UserRoleEnum
    op.execute("DROP TYPE userroleenum")

    # ### end Alembic commands ###
