"""add_forecast_expenses_table

Revision ID: e599fa6bdcf2
Revises: 7e7d9de8ea57
Create Date: 2025-10-24 13:26:45.972205+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e599fa6bdcf2'
down_revision: Union[str, None] = '7e7d9de8ea57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_regular', sa.Boolean(), nullable=False),
    sa.Column('based_on_expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['based_on_expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_expenses_forecast_date'), 'forecast_expenses', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_expenses_id'), 'forecast_expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_expenses_id'), table_name='forecast_expenses')
    op.drop_index(op.f('ix_forecast_expenses_forecast_date'), table_name='forecast_expenses')
    op.drop_table('forecast_expenses')
    # ### end Alembic commands ###
