"""add day_type to daily_work_records

Revision ID: 01af78d1dd58
Revises: 509126e8026b
Create Date: 2025-11-20 10:32:26.026885+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01af78d1dd58'
down_revision: Union[str, None] = '509126e8026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    day_type_enum = sa.Enum('WORK', 'UNPAID_LEAVE', 'SICK_LEAVE', 'VACATION', 'WEEKEND', 'HOLIDAY', name='daytypeenum')
    day_type_enum.create(op.get_bind(), checkfirst=True)

    # Add column with default value
    op.add_column('daily_work_records', sa.Column('day_type', day_type_enum, nullable=False, server_default='WORK'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop column
    op.drop_column('daily_work_records', 'day_type')

    # Drop enum type
    day_type_enum = sa.Enum('WORK', 'UNPAID_LEAVE', 'SICK_LEAVE', 'VACATION', 'WEEKEND', 'HOLIDAY', name='daytypeenum')
    day_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
