"""add_tax_rates_table

Revision ID: b631c554e247
Revises: 149bebc15bde
Create Date: 2025-11-18 08:09:02.586102+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b631c554e247'
down_revision: Union[str, None] = '149bebc15bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.Enum('INCOME_TAX', 'PENSION_FUND', 'MEDICAL_INSURANCE', 'SOCIAL_INSURANCE', 'INJURY_INSURANCE', name='taxtypeenum'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rate_above_threshold', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_rate_effective_date', 'tax_rates', ['effective_from', 'effective_to'], unique=False)
    op.create_index('idx_tax_rate_type_active', 'tax_rates', ['tax_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_tax_rates_department_id'), 'tax_rates', ['department_id'], unique=False)
    op.create_index(op.f('ix_tax_rates_effective_from'), 'tax_rates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_tax_rates_effective_to'), 'tax_rates', ['effective_to'], unique=False)
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    op.create_index(op.f('ix_tax_rates_is_active'), 'tax_rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_tax_rates_tax_type'), 'tax_rates', ['tax_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_rates_tax_type'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_is_active'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_effective_to'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_effective_from'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_department_id'), table_name='tax_rates')
    op.drop_index('idx_tax_rate_type_active', table_name='tax_rates')
    op.drop_index('idx_tax_rate_effective_date', table_name='tax_rates')
    op.drop_table('tax_rates')
    # ### end Alembic commands ###
