"""add 1c integration fields and unique constraints to prevent duplicates

Revision ID: faf79e6ef6e8
Revises: 158ce187a936
Create Date: 2025-11-16 15:43:48.860550+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf79e6ef6e8'
down_revision: Union[str, None] = '158ce187a936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip bank_transactions column type changes (data too long)
    # op.alter_column('bank_transactions', 'counterparty_account',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    # op.alter_column('bank_transactions', 'account_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    op.add_column('contractors', sa.Column('kpp', sa.String(length=20), nullable=True))
    op.add_column('contractors', sa.Column('external_id_1c', sa.String(length=100), nullable=True))
    op.create_index('idx_contractor_external_id_1c_dept', 'contractors', ['external_id_1c', 'department_id'], unique=True)
    op.create_index(op.f('ix_contractors_external_id_1c'), 'contractors', ['external_id_1c'], unique=False)
    op.create_index('idx_expense_external_id_1c_dept', 'expenses', ['external_id_1c', 'department_id'], unique=True)
    op.add_column('organizations', sa.Column('external_id_1c', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('full_name', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('short_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('inn', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('kpp', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organizations_department_id'), 'organizations', ['department_id'], unique=False)
    op.create_index(op.f('ix_organizations_external_id_1c'), 'organizations', ['external_id_1c'], unique=True)
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=False)
    op.create_foreign_key(None, 'organizations', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_external_id_1c'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_department_id'), table_name='organizations')
    op.drop_column('organizations', 'department_id')
    op.drop_column('organizations', 'kpp')
    op.drop_column('organizations', 'inn')
    op.drop_column('organizations', 'short_name')
    op.drop_column('organizations', 'full_name')
    op.drop_column('organizations', 'external_id_1c')
    op.drop_index('idx_expense_external_id_1c_dept', table_name='expenses')
    op.drop_index(op.f('ix_contractors_external_id_1c'), table_name='contractors')
    op.drop_index('idx_contractor_external_id_1c_dept', table_name='contractors')
    op.drop_column('contractors', 'external_id_1c')
    op.drop_column('contractors', 'kpp')
    # Skip bank_transactions column type changes (skipped in upgrade)
    # op.alter_column('bank_transactions', 'account_number',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    # op.alter_column('bank_transactions', 'counterparty_account',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    # ### end Alembic commands ###
