"""add credit portfolio tables with unique operation_id

Revision ID: 49720a832653
Revises: add_bank_transactions_001
Create Date: 2025-11-14 11:17:13.116715+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49720a832653'
down_revision: Union[str, None] = 'add_bank_transactions_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_bank_accounts_account_number'), 'fin_bank_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_fin_bank_accounts_department_id'), 'fin_bank_accounts', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_bank_accounts_is_active'), 'fin_bank_accounts', ['is_active'], unique=False)
    op.create_index('ix_fin_bank_accounts_number_dept', 'fin_bank_accounts', ['account_number', 'department_id'], unique=True)
    op.create_table('fin_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_number', sa.String(length=255), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_contracts_contract_date'), 'fin_contracts', ['contract_date'], unique=False)
    op.create_index(op.f('ix_fin_contracts_contract_number'), 'fin_contracts', ['contract_number'], unique=False)
    op.create_index(op.f('ix_fin_contracts_department_id'), 'fin_contracts', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_contracts_is_active'), 'fin_contracts', ['is_active'], unique=False)
    op.create_index('ix_fin_contracts_number_dept', 'fin_contracts', ['contract_number', 'department_id'], unique=True)
    op.create_table('fin_import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.Column('processing_time_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_import_logs_department_id'), 'fin_import_logs', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_import_logs_import_date'), 'fin_import_logs', ['import_date'], unique=False)
    op.create_index(op.f('ix_fin_import_logs_source_file'), 'fin_import_logs', ['source_file'], unique=False)
    op.create_index(op.f('ix_fin_import_logs_status'), 'fin_import_logs', ['status'], unique=False)
    op.create_index(op.f('ix_fin_import_logs_table_name'), 'fin_import_logs', ['table_name'], unique=False)
    op.create_table('fin_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_organizations_department_id'), 'fin_organizations', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_organizations_is_active'), 'fin_organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_fin_organizations_name'), 'fin_organizations', ['name'], unique=False)
    op.create_index('ix_fin_organizations_name_dept', 'fin_organizations', ['name', 'department_id'], unique=True)
    op.create_table('fin_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=255), nullable=True),
    sa.Column('accounting_account', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('recipient_account', sa.String(length=255), nullable=True),
    sa.Column('debit_account', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_article', sa.String(length=255), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tax_period', sa.String(length=10), nullable=True),
    sa.Column('unconfirmed_by_bank', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['fin_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['fin_contracts.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['fin_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_expenses_bank_account_id'), 'fin_expenses', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_fin_expenses_contract_id'), 'fin_expenses', ['contract_id'], unique=False)
    op.create_index(op.f('ix_fin_expenses_department_id'), 'fin_expenses', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_expenses_document_date'), 'fin_expenses', ['document_date'], unique=False)
    op.create_index(op.f('ix_fin_expenses_expense_article'), 'fin_expenses', ['expense_article'], unique=False)
    op.create_index(op.f('ix_fin_expenses_is_active'), 'fin_expenses', ['is_active'], unique=False)
    op.create_index('ix_fin_expenses_operation_dept', 'fin_expenses', ['operation_id', 'department_id'], unique=True)
    op.create_index(op.f('ix_fin_expenses_operation_id'), 'fin_expenses', ['operation_id'], unique=True)
    op.create_index(op.f('ix_fin_expenses_organization_id'), 'fin_expenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fin_expenses_recipient'), 'fin_expenses', ['recipient'], unique=False)
    op.create_table('fin_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=255), nullable=True),
    sa.Column('accounting_account', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('payer', sa.String(length=255), nullable=True),
    sa.Column('payer_account', sa.String(length=255), nullable=True),
    sa.Column('settlement_account', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['fin_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['fin_contracts.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['fin_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_receipts_bank_account_id'), 'fin_receipts', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_fin_receipts_contract_id'), 'fin_receipts', ['contract_id'], unique=False)
    op.create_index(op.f('ix_fin_receipts_department_id'), 'fin_receipts', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_receipts_document_date'), 'fin_receipts', ['document_date'], unique=False)
    op.create_index(op.f('ix_fin_receipts_is_active'), 'fin_receipts', ['is_active'], unique=False)
    op.create_index('ix_fin_receipts_operation_dept', 'fin_receipts', ['operation_id', 'department_id'], unique=True)
    op.create_index(op.f('ix_fin_receipts_operation_id'), 'fin_receipts', ['operation_id'], unique=True)
    op.create_index(op.f('ix_fin_receipts_organization_id'), 'fin_receipts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fin_receipts_payer'), 'fin_receipts', ['payer'], unique=False)
    op.create_table('fin_expense_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_operation_id', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=255), nullable=True),
    sa.Column('repayment_type', sa.String(length=100), nullable=True),
    sa.Column('settlement_account', sa.String(length=100), nullable=True),
    sa.Column('advance_account', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=255), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('settlement_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expense_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_in_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['expense_operation_id'], ['fin_expenses.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_expense_details_contract_number'), 'fin_expense_details', ['contract_number'], unique=False)
    op.create_index(op.f('ix_fin_expense_details_department_id'), 'fin_expense_details', ['department_id'], unique=False)
    op.create_index(op.f('ix_fin_expense_details_expense_operation_id'), 'fin_expense_details', ['expense_operation_id'], unique=False)
    op.create_index(op.f('ix_fin_expense_details_payment_type'), 'fin_expense_details', ['payment_type'], unique=False)
    op.create_index(op.f('ix_fin_expense_details_settlement_account'), 'fin_expense_details', ['settlement_account'], unique=False)
    # Use IF EXISTS to avoid failures on partially-migrated databases
    op.execute('DROP INDEX IF EXISTS idx_receipts_amount')
    op.execute('DROP INDEX IF EXISTS idx_receipts_bank_account_id')
    op.execute('DROP INDEX IF EXISTS idx_receipts_contract_date')
    op.execute('DROP INDEX IF EXISTS idx_receipts_contract_id')
    op.execute('DROP INDEX IF EXISTS idx_receipts_created_at')
    op.execute('DROP INDEX IF EXISTS idx_receipts_document_date')
    op.execute('DROP INDEX IF EXISTS idx_receipts_operation_id')
    op.execute('DROP INDEX IF EXISTS idx_receipts_org_amount')
    op.execute('DROP INDEX IF EXISTS idx_receipts_org_date')
    op.execute('DROP INDEX IF EXISTS idx_receipts_organization_id')
    op.execute('DROP INDEX IF EXISTS idx_receipts_payer')
    op.execute('DROP INDEX IF EXISTS idx_receipts_payment_purpose_gin')
    op.execute('DROP TABLE IF EXISTS receipts CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_contracts_active')
    op.execute('DROP INDEX IF EXISTS idx_contracts_counterparty')
    op.execute('DROP INDEX IF EXISTS idx_contracts_organization_id')
    op.execute('DROP INDEX IF EXISTS ix_contracts_contract_date')
    op.execute('DROP INDEX IF EXISTS ix_contracts_contract_number')
    op.execute('DROP TABLE IF EXISTS contracts CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_bank_accounts_active')
    op.execute('DROP INDEX IF EXISTS idx_bank_accounts_organization_id')
    op.execute('DROP INDEX IF EXISTS ix_bank_accounts_account_number')
    op.execute('DROP TABLE IF EXISTS bank_accounts CASCADE')
    op.execute('DROP TABLE IF EXISTS schema_migrations CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_failed')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_import_date')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_source_file')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_status')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_table_name')
    op.execute('DROP INDEX IF EXISTS idx_import_logs_table_status')
    op.execute('DROP TABLE IF EXISTS import_logs CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_expense_details_contract')
    op.execute('DROP INDEX IF EXISTS idx_expense_details_expense_id')
    op.execute('DROP INDEX IF EXISTS idx_expense_details_payment_type')
    op.execute('DROP INDEX IF EXISTS idx_expense_details_settlement_account')
    op.execute('DROP INDEX IF EXISTS idx_expense_details_unique')
    op.execute('DROP TABLE IF EXISTS expense_details CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_organizations_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_organizations_active', 'organizations', ['is_active', 'name'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('expense_details',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('expense_operation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Ссылка на операцию списания'),
    sa.Column('contract_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('repayment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('settlement_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('advance_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('settlement_rate', sa.NUMERIC(precision=15, scale=6), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('settlement_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('vat_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('expense_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('vat_in_expense', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='expense_details_pkey'),
    comment='Расшифровка операций списания'
    )
    op.create_index('idx_expense_details_unique', 'expense_details', ['expense_operation_id', sa.text("COALESCE(contract_number, ''::character varying)"), sa.text("COALESCE(payment_type, ''::character varying)"), sa.text('COALESCE(payment_amount, 0::numeric)'), sa.text("COALESCE(settlement_account, ''::character varying)")], unique=False)
    op.create_index('idx_expense_details_settlement_account', 'expense_details', ['settlement_account'], unique=False)
    op.create_index('idx_expense_details_payment_type', 'expense_details', ['payment_type'], unique=False)
    op.create_index('idx_expense_details_expense_id', 'expense_details', ['expense_operation_id'], unique=False)
    op.create_index('idx_expense_details_contract', 'expense_details', ['contract_number'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('import_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rows_inserted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rows_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rows_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('processing_time_seconds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='import_logs_pkey'),
    comment='Журнал импорта данных из файлов'
    )
    op.create_index('idx_import_logs_table_status', 'import_logs', ['table_name', 'status', sa.text('import_date DESC')], unique=False)
    op.create_index('idx_import_logs_table_name', 'import_logs', ['table_name'], unique=False)
    op.create_index('idx_import_logs_status', 'import_logs', ['status'], unique=False)
    op.create_index('idx_import_logs_source_file', 'import_logs', ['source_file'], unique=False)
    op.create_index('idx_import_logs_import_date', 'import_logs', [sa.text('import_date DESC')], unique=False)
    op.create_index('idx_import_logs_failed', 'import_logs', [sa.text('import_date DESC')], unique=False, postgresql_where="((status)::text = 'failed'::text)")
    op.create_table('schema_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schema_migrations_pkey'),
    sa.UniqueConstraint('migration_name', name='schema_migrations_migration_name_key')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bank_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='bank_accounts_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bank_accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_bank_accounts_account_number', 'bank_accounts', ['account_number'], unique=False)
    op.create_index('idx_bank_accounts_organization_id', 'bank_accounts', ['organization_id'], unique=False)
    op.create_index('idx_bank_accounts_active', 'bank_accounts', ['is_active', 'account_number'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contracts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('contract_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contract_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('counterparty', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='contracts_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_contracts_contract_number', 'contracts', ['contract_number'], unique=False)
    op.create_index('ix_contracts_contract_date', 'contracts', ['contract_date'], unique=False)
    op.create_index('idx_contracts_organization_id', 'contracts', ['organization_id'], unique=False)
    op.create_index('idx_contracts_counterparty', 'contracts', ['counterparty'], unique=False, postgresql_where='(counterparty IS NOT NULL)')
    op.create_index('idx_contracts_active', 'contracts', ['is_active', sa.text('contract_date DESC')], unique=False, postgresql_where='(is_active = true)')
    op.create_table('receipts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Уникальный идентификатор операции из 1С'),
    sa.Column('operation_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('accounting_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('payer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payer_account', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('settlement_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contract_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('commission', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsible_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name='receipts_bank_account_id_fkey'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='receipts_contract_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='receipts_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='receipts_pkey'),
    sa.UniqueConstraint('operation_id', name='receipts_operation_id_key'),
    comment='Поступления денежных средств на расчетные счета'
    )
    op.create_index('idx_receipts_payment_purpose_gin', 'receipts', [sa.text("to_tsvector('russian'::regconfig, COALESCE(payment_purpose, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_receipts_payer', 'receipts', ['payer'], unique=False)
    op.create_index('idx_receipts_organization_id', 'receipts', ['organization_id'], unique=False)
    op.create_index('idx_receipts_org_date', 'receipts', ['organization_id', sa.text('document_date DESC')], unique=False, postgresql_where='(organization_id IS NOT NULL)')
    op.create_index('idx_receipts_org_amount', 'receipts', ['organization_id', sa.text('amount DESC')], unique=False, postgresql_where='((organization_id IS NOT NULL) AND (amount > (0)::numeric))')
    op.create_index('idx_receipts_operation_id', 'receipts', ['operation_id'], unique=False)
    op.create_index('idx_receipts_document_date', 'receipts', [sa.text('document_date DESC')], unique=False)
    op.create_index('idx_receipts_created_at', 'receipts', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_receipts_contract_id', 'receipts', ['contract_id'], unique=False)
    op.create_index('idx_receipts_contract_date', 'receipts', ['contract_id', sa.text('document_date DESC')], unique=False, postgresql_where='(contract_id IS NOT NULL)')
    op.create_index('idx_receipts_bank_account_id', 'receipts', ['bank_account_id'], unique=False)
    op.create_index('idx_receipts_amount', 'receipts', ['amount'], unique=False)
    op.drop_index(op.f('ix_fin_expense_details_settlement_account'), table_name='fin_expense_details')
    op.drop_index(op.f('ix_fin_expense_details_payment_type'), table_name='fin_expense_details')
    op.drop_index(op.f('ix_fin_expense_details_expense_operation_id'), table_name='fin_expense_details')
    op.drop_index(op.f('ix_fin_expense_details_department_id'), table_name='fin_expense_details')
    op.drop_index(op.f('ix_fin_expense_details_contract_number'), table_name='fin_expense_details')
    op.drop_table('fin_expense_details')
    op.drop_index(op.f('ix_fin_receipts_payer'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_organization_id'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_operation_id'), table_name='fin_receipts')
    op.drop_index('ix_fin_receipts_operation_dept', table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_is_active'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_document_date'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_department_id'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_contract_id'), table_name='fin_receipts')
    op.drop_index(op.f('ix_fin_receipts_bank_account_id'), table_name='fin_receipts')
    op.drop_table('fin_receipts')
    op.drop_index(op.f('ix_fin_expenses_recipient'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_organization_id'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_operation_id'), table_name='fin_expenses')
    op.drop_index('ix_fin_expenses_operation_dept', table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_is_active'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_expense_article'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_document_date'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_department_id'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_contract_id'), table_name='fin_expenses')
    op.drop_index(op.f('ix_fin_expenses_bank_account_id'), table_name='fin_expenses')
    op.drop_table('fin_expenses')
    op.drop_index('ix_fin_organizations_name_dept', table_name='fin_organizations')
    op.drop_index(op.f('ix_fin_organizations_name'), table_name='fin_organizations')
    op.drop_index(op.f('ix_fin_organizations_is_active'), table_name='fin_organizations')
    op.drop_index(op.f('ix_fin_organizations_department_id'), table_name='fin_organizations')
    op.drop_table('fin_organizations')
    op.drop_index(op.f('ix_fin_import_logs_table_name'), table_name='fin_import_logs')
    op.drop_index(op.f('ix_fin_import_logs_status'), table_name='fin_import_logs')
    op.drop_index(op.f('ix_fin_import_logs_source_file'), table_name='fin_import_logs')
    op.drop_index(op.f('ix_fin_import_logs_import_date'), table_name='fin_import_logs')
    op.drop_index(op.f('ix_fin_import_logs_department_id'), table_name='fin_import_logs')
    op.drop_table('fin_import_logs')
    op.drop_index('ix_fin_contracts_number_dept', table_name='fin_contracts')
    op.drop_index(op.f('ix_fin_contracts_is_active'), table_name='fin_contracts')
    op.drop_index(op.f('ix_fin_contracts_department_id'), table_name='fin_contracts')
    op.drop_index(op.f('ix_fin_contracts_contract_number'), table_name='fin_contracts')
    op.drop_index(op.f('ix_fin_contracts_contract_date'), table_name='fin_contracts')
    op.drop_table('fin_contracts')
    op.drop_index('ix_fin_bank_accounts_number_dept', table_name='fin_bank_accounts')
    op.drop_index(op.f('ix_fin_bank_accounts_is_active'), table_name='fin_bank_accounts')
    op.drop_index(op.f('ix_fin_bank_accounts_department_id'), table_name='fin_bank_accounts')
    op.drop_index(op.f('ix_fin_bank_accounts_account_number'), table_name='fin_bank_accounts')
    op.drop_table('fin_bank_accounts')
    # ### end Alembic commands ###
