"""add external_id_1c to expenses for 1C OData sync

Revision ID: 158ce187a936
Revises: c10198cd2bcb
Create Date: 2025-11-16 15:31:57.125560+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158ce187a936'
down_revision: Union[str, None] = 'c10198cd2bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('expenses', sa.Column('external_id_1c', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_expenses_external_id_1c'), 'expenses', ['external_id_1c'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_external_id_1c'), table_name='expenses')
    op.drop_column('expenses', 'external_id_1c')
    op.alter_column('bank_transactions', 'account_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'counterparty_account',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
