"""add processed_invoices table for AI invoice processing

Revision ID: feb0bf4080a5
Revises: add_api_tokens_001
Create Date: 2025-11-05 16:56:01.572047+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb0bf4080a5'
down_revision: Union[str, None] = 'add_api_tokens_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ocr_processing_time_sec', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_inn', sa.String(length=12), nullable=True),
    sa.Column('supplier_kpp', sa.String(length=9), nullable=True),
    sa.Column('supplier_bank_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_bik', sa.String(length=9), nullable=True),
    sa.Column('supplier_account', sa.String(length=20), nullable=True),
    sa.Column('amount_without_vat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'ERROR', 'MANUAL_REVIEW', 'EXPENSE_CREATED', name='invoiceprocessingstatusenum'), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('ai_processing_time_sec', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('expense_created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_invoice_date', 'processed_invoices', ['invoice_date'], unique=False)
    op.create_index('idx_processed_invoice_dept', 'processed_invoices', ['department_id'], unique=False)
    op.create_index('idx_processed_invoice_inn', 'processed_invoices', ['supplier_inn'], unique=False)
    op.create_index('idx_processed_invoice_number', 'processed_invoices', ['invoice_number'], unique=False)
    op.create_index('idx_processed_invoice_status', 'processed_invoices', ['status'], unique=False)
    op.create_index('idx_processed_invoice_uploaded_at', 'processed_invoices', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_processed_invoices_department_id'), 'processed_invoices', ['department_id'], unique=False)
    op.create_index(op.f('ix_processed_invoices_id'), 'processed_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_processed_invoices_invoice_number'), 'processed_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_processed_invoices_is_active'), 'processed_invoices', ['is_active'], unique=False)
    op.create_index(op.f('ix_processed_invoices_status'), 'processed_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_processed_invoices_supplier_inn'), 'processed_invoices', ['supplier_inn'], unique=False)
    op.drop_constraint('uq_api_tokens_token_key', 'api_tokens', type_='unique')
    op.drop_index('idx_api_token_key', table_name='api_tokens')
    op.create_index('idx_api_token_key', 'api_tokens', ['token_key'], unique=False)
    op.create_index(op.f('ix_api_tokens_department_id'), 'api_tokens', ['department_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_key'), 'api_tokens', ['token_key'], unique=True)
    op.create_index(op.f('ix_customer_metrics_department_id'), 'customer_metrics', ['department_id'], unique=False)
    op.drop_constraint('uq_organizations_name', 'organizations', type_='unique')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_revenue_actuals_department_id'), 'revenue_actuals', ['department_id'], unique=False)
    op.drop_constraint('revenue_categories_code_key', 'revenue_categories', type_='unique')
    op.drop_index('ix_revenue_categories_code', table_name='revenue_categories')
    op.create_index(op.f('ix_revenue_categories_code'), 'revenue_categories', ['code'], unique=True)
    op.create_index(op.f('ix_revenue_categories_department_id'), 'revenue_categories', ['department_id'], unique=False)
    op.create_index(op.f('ix_revenue_categories_is_active'), 'revenue_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_revenue_forecasts_department_id'), 'revenue_forecasts', ['department_id'], unique=False)
    op.create_index(op.f('ix_revenue_plan_details_department_id'), 'revenue_plan_details', ['department_id'], unique=False)
    op.create_index(op.f('ix_revenue_plans_department_id'), 'revenue_plans', ['department_id'], unique=False)
    op.create_index(op.f('ix_revenue_streams_department_id'), 'revenue_streams', ['department_id'], unique=False)
    op.create_index(op.f('ix_revenue_streams_is_active'), 'revenue_streams', ['is_active'], unique=False)
    op.create_index(op.f('ix_seasonality_coefficients_department_id'), 'seasonality_coefficients', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasonality_coefficients_department_id'), table_name='seasonality_coefficients')
    op.drop_index(op.f('ix_revenue_streams_is_active'), table_name='revenue_streams')
    op.drop_index(op.f('ix_revenue_streams_department_id'), table_name='revenue_streams')
    op.drop_index(op.f('ix_revenue_plans_department_id'), table_name='revenue_plans')
    op.drop_index(op.f('ix_revenue_plan_details_department_id'), table_name='revenue_plan_details')
    op.drop_index(op.f('ix_revenue_forecasts_department_id'), table_name='revenue_forecasts')
    op.drop_index(op.f('ix_revenue_categories_is_active'), table_name='revenue_categories')
    op.drop_index(op.f('ix_revenue_categories_department_id'), table_name='revenue_categories')
    op.drop_index(op.f('ix_revenue_categories_code'), table_name='revenue_categories')
    op.create_index('ix_revenue_categories_code', 'revenue_categories', ['code'], unique=False)
    op.create_unique_constraint('revenue_categories_code_key', 'revenue_categories', ['code'])
    op.drop_index(op.f('ix_revenue_actuals_department_id'), table_name='revenue_actuals')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_unique_constraint('uq_organizations_name', 'organizations', ['name'])
    op.drop_index(op.f('ix_customer_metrics_department_id'), table_name='customer_metrics')
    op.drop_index(op.f('ix_api_tokens_token_key'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_department_id'), table_name='api_tokens')
    op.drop_index('idx_api_token_key', table_name='api_tokens')
    op.create_index('idx_api_token_key', 'api_tokens', ['token_key'], unique=False)
    op.create_unique_constraint('uq_api_tokens_token_key', 'api_tokens', ['token_key'])
    op.drop_index(op.f('ix_processed_invoices_supplier_inn'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_status'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_is_active'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_invoice_number'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_id'), table_name='processed_invoices')
    op.drop_index(op.f('ix_processed_invoices_department_id'), table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_uploaded_at', table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_status', table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_number', table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_inn', table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_dept', table_name='processed_invoices')
    op.drop_index('idx_processed_invoice_date', table_name='processed_invoices')
    op.drop_table('processed_invoices')
    # ### end Alembic commands ###
