"""add birth_date to employees

Revision ID: 149bebc15bde
Revises: 50c93f7ffd74
Create Date: 2025-11-18 06:54:22.597981+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149bebc15bde'
down_revision: Union[str, None] = '50c93f7ffd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'birth_date')
    # ### end Alembic commands ###
