"""make_expense_category_id_nullable

Revision ID: 39fcb0613cd9
Revises: eb520a6d5cae
Create Date: 2025-10-26 09:03:55.393727+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fcb0613cd9'
down_revision: Union[str, None] = 'eb520a6d5cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_log_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.drop_index('ix_contractors_inn', table_name='contractors')
    op.create_index(op.f('ix_contractors_inn'), 'contractors', ['inn'], unique=False)
    op.alter_column('expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_expenses_number', table_name='expenses')
    op.create_index(op.f('ix_expenses_number'), 'expenses', ['number'], unique=False)
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.drop_index(op.f('ix_expenses_number'), table_name='expenses')
    op.create_index('ix_expenses_number', 'expenses', ['number'], unique=False)
    op.alter_column('expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_contractors_inn'), table_name='contractors')
    op.create_index('ix_contractors_inn', 'contractors', ['inn'], unique=False)
    op.drop_index('idx_audit_log_timestamp', table_name='audit_logs')
    # ### end Alembic commands ###
