"""add desired_payment_date to processed_invoices

Revision ID: 50c93f7ffd74
Revises: make_category_nullable
Create Date: 2025-11-17 19:38:15.642483+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c93f7ffd74'
down_revision: Union[str, None] = 'make_category_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_invoices', sa.Column('desired_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_invoices', 'desired_payment_date')
    # ### end Alembic commands ###
