"""add_import_tracking_fields_to_expenses

Revision ID: 7e7d9de8ea57
Revises: 98735387a296
Create Date: 2025-10-24 13:18:34.037525+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e7d9de8ea57'
down_revision: Union[str, None] = '98735387a296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_plans', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'APPROVED', name='budgetstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::budgetstatusenum"))

    # Add columns with default values for existing rows
    op.add_column('expenses', sa.Column('imported_from_ftp', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('expenses', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'needs_review')
    op.drop_column('expenses', 'imported_from_ftp')
    op.alter_column('budget_plans', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'APPROVED', name='budgetstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::budgetstatusenum"))
    # ### end Alembic commands ###
